// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authpb.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{0}
}

type CheckServerStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusRequest) Reset()         { *m = CheckServerStatusRequest{} }
func (m *CheckServerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusRequest) ProtoMessage()    {}
func (*CheckServerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{0}
}

func (m *CheckServerStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusRequest.Unmarshal(m, b)
}
func (m *CheckServerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusRequest.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusRequest.Merge(m, src)
}
func (m *CheckServerStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusRequest.Size(m)
}
func (m *CheckServerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusRequest proto.InternalMessageInfo

type CheckServerStatusResponse struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusResponse) Reset()         { *m = CheckServerStatusResponse{} }
func (m *CheckServerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusResponse) ProtoMessage()    {}
func (*CheckServerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{1}
}

func (m *CheckServerStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusResponse.Unmarshal(m, b)
}
func (m *CheckServerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusResponse.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusResponse.Merge(m, src)
}
func (m *CheckServerStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusResponse.Size(m)
}
func (m *CheckServerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusResponse proto.InternalMessageInfo

func (m *CheckServerStatusResponse) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *CheckServerStatusResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CheckServerStatusResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CheckServerStatusResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CheckServerStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RegisterAccountRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	CompanyTerms         bool     `protobuf:"varint,7,opt,name=company_terms,json=companyTerms,proto3" json:"company_terms,omitempty"`
	GovtTerms            bool     `protobuf:"varint,8,opt,name=govt_terms,json=govtTerms,proto3" json:"govt_terms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{2}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterAccountRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *RegisterAccountRequest) GetCompanyTerms() bool {
	if m != nil {
		return m.CompanyTerms
	}
	return false
}

func (m *RegisterAccountRequest) GetGovtTerms() bool {
	if m != nil {
		return m.GovtTerms
	}
	return false
}

type RegisterAccountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{3}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *RegisterAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GenerateDeviceKeyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateDeviceKeyRequest) Reset()         { *m = GenerateDeviceKeyRequest{} }
func (m *GenerateDeviceKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateDeviceKeyRequest) ProtoMessage()    {}
func (*GenerateDeviceKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{4}
}

func (m *GenerateDeviceKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateDeviceKeyRequest.Unmarshal(m, b)
}
func (m *GenerateDeviceKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateDeviceKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateDeviceKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateDeviceKeyRequest.Merge(m, src)
}
func (m *GenerateDeviceKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateDeviceKeyRequest.Size(m)
}
func (m *GenerateDeviceKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateDeviceKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateDeviceKeyRequest proto.InternalMessageInfo

func (m *GenerateDeviceKeyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GenerateDeviceKeyResponse struct {
	DeviceKey            string   `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateDeviceKeyResponse) Reset()         { *m = GenerateDeviceKeyResponse{} }
func (m *GenerateDeviceKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateDeviceKeyResponse) ProtoMessage()    {}
func (*GenerateDeviceKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{5}
}

func (m *GenerateDeviceKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateDeviceKeyResponse.Unmarshal(m, b)
}
func (m *GenerateDeviceKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateDeviceKeyResponse.Marshal(b, m, deterministic)
}
func (m *GenerateDeviceKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateDeviceKeyResponse.Merge(m, src)
}
func (m *GenerateDeviceKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateDeviceKeyResponse.Size(m)
}
func (m *GenerateDeviceKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateDeviceKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateDeviceKeyResponse proto.InternalMessageInfo

func (m *GenerateDeviceKeyResponse) GetDeviceKey() string {
	if m != nil {
		return m.DeviceKey
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateAccountRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{8}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateAccountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{9}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *UpdateAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAccountDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDetailsRequest) Reset()         { *m = GetAccountDetailsRequest{} }
func (m *GetAccountDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountDetailsRequest) ProtoMessage()    {}
func (*GetAccountDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{10}
}

func (m *GetAccountDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDetailsRequest.Unmarshal(m, b)
}
func (m *GetAccountDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDetailsRequest.Merge(m, src)
}
func (m *GetAccountDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountDetailsRequest.Size(m)
}
func (m *GetAccountDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDetailsRequest proto.InternalMessageInfo

type GetAccountDetailsResponse struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDetailsResponse) Reset()         { *m = GetAccountDetailsResponse{} }
func (m *GetAccountDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountDetailsResponse) ProtoMessage()    {}
func (*GetAccountDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{11}
}

func (m *GetAccountDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDetailsResponse.Unmarshal(m, b)
}
func (m *GetAccountDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDetailsResponse.Merge(m, src)
}
func (m *GetAccountDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountDetailsResponse.Size(m)
}
func (m *GetAccountDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDetailsResponse proto.InternalMessageInfo

func (m *GetAccountDetailsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{12}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{13}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ChangePasswordResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAllAccountsRequest struct {
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllAccountsRequest) Reset()         { *m = GetAllAccountsRequest{} }
func (m *GetAllAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllAccountsRequest) ProtoMessage()    {}
func (*GetAllAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{14}
}

func (m *GetAllAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAccountsRequest.Unmarshal(m, b)
}
func (m *GetAllAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAccountsRequest.Merge(m, src)
}
func (m *GetAllAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllAccountsRequest.Size(m)
}
func (m *GetAllAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAccountsRequest proto.InternalMessageInfo

func (m *GetAllAccountsRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetAllAccountsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetAllAccountsResponse struct {
	FfId                 string   `protobuf:"bytes,1,opt,name=ff_id,json=ffId,proto3" json:"ff_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllAccountsResponse) Reset()         { *m = GetAllAccountsResponse{} }
func (m *GetAllAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllAccountsResponse) ProtoMessage()    {}
func (*GetAllAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{15}
}

func (m *GetAllAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAccountsResponse.Unmarshal(m, b)
}
func (m *GetAllAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAccountsResponse.Merge(m, src)
}
func (m *GetAllAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllAccountsResponse.Size(m)
}
func (m *GetAllAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAccountsResponse proto.InternalMessageInfo

func (m *GetAllAccountsResponse) GetFfId() string {
	if m != nil {
		return m.FfId
	}
	return ""
}

func (m *GetAllAccountsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetAllAccountsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetAllAccountsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetAllAccountsResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetAllAccountsResponse) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *GetAllAccountsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAllSessionDetailsRequest struct {
	FfId                 string   `protobuf:"bytes,1,opt,name=ff_id,json=ffId,proto3" json:"ff_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSessionDetailsRequest) Reset()         { *m = GetAllSessionDetailsRequest{} }
func (m *GetAllSessionDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllSessionDetailsRequest) ProtoMessage()    {}
func (*GetAllSessionDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{16}
}

func (m *GetAllSessionDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Unmarshal(m, b)
}
func (m *GetAllSessionDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllSessionDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSessionDetailsRequest.Merge(m, src)
}
func (m *GetAllSessionDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Size(m)
}
func (m *GetAllSessionDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSessionDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSessionDetailsRequest proto.InternalMessageInfo

func (m *GetAllSessionDetailsRequest) GetFfId() string {
	if m != nil {
		return m.FfId
	}
	return ""
}

type GetAllSessionDetailsResponse struct {
	FsId                 string   `protobuf:"bytes,1,opt,name=fs_id,json=fsId,proto3" json:"fs_id,omitempty"`
	LoggedIn             string   `protobuf:"bytes,2,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	CurrentStatus        string   `protobuf:"bytes,3,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	LastPing             string   `protobuf:"bytes,4,opt,name=last_ping,json=lastPing,proto3" json:"last_ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSessionDetailsResponse) Reset()         { *m = GetAllSessionDetailsResponse{} }
func (m *GetAllSessionDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllSessionDetailsResponse) ProtoMessage()    {}
func (*GetAllSessionDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{17}
}

func (m *GetAllSessionDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Unmarshal(m, b)
}
func (m *GetAllSessionDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllSessionDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSessionDetailsResponse.Merge(m, src)
}
func (m *GetAllSessionDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Size(m)
}
func (m *GetAllSessionDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSessionDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSessionDetailsResponse proto.InternalMessageInfo

func (m *GetAllSessionDetailsResponse) GetFsId() string {
	if m != nil {
		return m.FsId
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetLoggedIn() string {
	if m != nil {
		return m.LoggedIn
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetCurrentStatus() string {
	if m != nil {
		return m.CurrentStatus
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetLastPing() string {
	if m != nil {
		return m.LastPing
	}
	return ""
}

type CheckUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameRequest) Reset()         { *m = CheckUsernameRequest{} }
func (m *CheckUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameRequest) ProtoMessage()    {}
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{18}
}

func (m *CheckUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameRequest.Unmarshal(m, b)
}
func (m *CheckUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameRequest.Marshal(b, m, deterministic)
}
func (m *CheckUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameRequest.Merge(m, src)
}
func (m *CheckUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameRequest.Size(m)
}
func (m *CheckUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameRequest proto.InternalMessageInfo

func (m *CheckUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CheckUsernameResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameResponse) Reset()         { *m = CheckUsernameResponse{} }
func (m *CheckUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameResponse) ProtoMessage()    {}
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{19}
}

func (m *CheckUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameResponse.Unmarshal(m, b)
}
func (m *CheckUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameResponse.Marshal(b, m, deterministic)
}
func (m *CheckUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameResponse.Merge(m, src)
}
func (m *CheckUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameResponse.Size(m)
}
func (m *CheckUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameResponse proto.InternalMessageInfo

func (m *CheckUsernameResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CheckUsernameResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UsernameAvailabilityRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameAvailabilityRequest) Reset()         { *m = UsernameAvailabilityRequest{} }
func (m *UsernameAvailabilityRequest) String() string { return proto.CompactTextString(m) }
func (*UsernameAvailabilityRequest) ProtoMessage()    {}
func (*UsernameAvailabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{20}
}

func (m *UsernameAvailabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameAvailabilityRequest.Unmarshal(m, b)
}
func (m *UsernameAvailabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameAvailabilityRequest.Marshal(b, m, deterministic)
}
func (m *UsernameAvailabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameAvailabilityRequest.Merge(m, src)
}
func (m *UsernameAvailabilityRequest) XXX_Size() int {
	return xxx_messageInfo_UsernameAvailabilityRequest.Size(m)
}
func (m *UsernameAvailabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameAvailabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameAvailabilityRequest proto.InternalMessageInfo

func (m *UsernameAvailabilityRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UsernameAvailabilityResponse struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameAvailabilityResponse) Reset()         { *m = UsernameAvailabilityResponse{} }
func (m *UsernameAvailabilityResponse) String() string { return proto.CompactTextString(m) }
func (*UsernameAvailabilityResponse) ProtoMessage()    {}
func (*UsernameAvailabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{21}
}

func (m *UsernameAvailabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameAvailabilityResponse.Unmarshal(m, b)
}
func (m *UsernameAvailabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameAvailabilityResponse.Marshal(b, m, deterministic)
}
func (m *UsernameAvailabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameAvailabilityResponse.Merge(m, src)
}
func (m *UsernameAvailabilityResponse) XXX_Size() int {
	return xxx_messageInfo_UsernameAvailabilityResponse.Size(m)
}
func (m *UsernameAvailabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameAvailabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameAvailabilityResponse proto.InternalMessageInfo

func (m *UsernameAvailabilityResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type EmailAvailabilityRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAvailabilityRequest) Reset()         { *m = EmailAvailabilityRequest{} }
func (m *EmailAvailabilityRequest) String() string { return proto.CompactTextString(m) }
func (*EmailAvailabilityRequest) ProtoMessage()    {}
func (*EmailAvailabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{22}
}

func (m *EmailAvailabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAvailabilityRequest.Unmarshal(m, b)
}
func (m *EmailAvailabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAvailabilityRequest.Marshal(b, m, deterministic)
}
func (m *EmailAvailabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAvailabilityRequest.Merge(m, src)
}
func (m *EmailAvailabilityRequest) XXX_Size() int {
	return xxx_messageInfo_EmailAvailabilityRequest.Size(m)
}
func (m *EmailAvailabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAvailabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAvailabilityRequest proto.InternalMessageInfo

func (m *EmailAvailabilityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailAvailabilityResponse struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAvailabilityResponse) Reset()         { *m = EmailAvailabilityResponse{} }
func (m *EmailAvailabilityResponse) String() string { return proto.CompactTextString(m) }
func (*EmailAvailabilityResponse) ProtoMessage()    {}
func (*EmailAvailabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{23}
}

func (m *EmailAvailabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAvailabilityResponse.Unmarshal(m, b)
}
func (m *EmailAvailabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAvailabilityResponse.Marshal(b, m, deterministic)
}
func (m *EmailAvailabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAvailabilityResponse.Merge(m, src)
}
func (m *EmailAvailabilityResponse) XXX_Size() int {
	return xxx_messageInfo_EmailAvailabilityResponse.Size(m)
}
func (m *EmailAvailabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAvailabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAvailabilityResponse proto.InternalMessageInfo

func (m *EmailAvailabilityResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type GetSystemDetailsRequest struct {
	HardwareName         string   `protobuf:"bytes,1,opt,name=hardware_name,json=hardwareName,proto3" json:"hardware_name,omitempty"`
	HardwareAddress      string   `protobuf:"bytes,2,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os                   string   `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Cpu                  string   `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemDetailsRequest) Reset()         { *m = GetSystemDetailsRequest{} }
func (m *GetSystemDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemDetailsRequest) ProtoMessage()    {}
func (*GetSystemDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{24}
}

func (m *GetSystemDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemDetailsRequest.Unmarshal(m, b)
}
func (m *GetSystemDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemDetailsRequest.Merge(m, src)
}
func (m *GetSystemDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemDetailsRequest.Size(m)
}
func (m *GetSystemDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemDetailsRequest proto.InternalMessageInfo

func (m *GetSystemDetailsRequest) GetHardwareName() string {
	if m != nil {
		return m.HardwareName
	}
	return ""
}

func (m *GetSystemDetailsRequest) GetHardwareAddress() string {
	if m != nil {
		return m.HardwareAddress
	}
	return ""
}

func (m *GetSystemDetailsRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *GetSystemDetailsRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *GetSystemDetailsRequest) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

type GetSystemDetailsResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemDetailsResponse) Reset()         { *m = GetSystemDetailsResponse{} }
func (m *GetSystemDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSystemDetailsResponse) ProtoMessage()    {}
func (*GetSystemDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{25}
}

func (m *GetSystemDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemDetailsResponse.Unmarshal(m, b)
}
func (m *GetSystemDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetSystemDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemDetailsResponse.Merge(m, src)
}
func (m *GetSystemDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSystemDetailsResponse.Size(m)
}
func (m *GetSystemDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemDetailsResponse proto.InternalMessageInfo

func (m *GetSystemDetailsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetSystemDetailsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	TotalSize            string   `protobuf:"bytes,2,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	Received             string   `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{26}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetTotalSize() string {
	if m != nil {
		return m.TotalSize
	}
	return ""
}

func (m *Chunk) GetReceived() string {
	if m != nil {
		return m.Received
	}
	return ""
}

type UploadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{27}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

type UploadStatus struct {
	Message              string           `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code                 UploadStatusCode `protobuf:"varint,2,opt,name=Code,proto3,enum=authpb.UploadStatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{28}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadStatus) GetCode() UploadStatusCode {
	if m != nil {
		return m.Code
	}
	return UploadStatusCode_Unknown
}

type SDKFogfindRequest struct {
	Username             string         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DeviceKey            string         `protobuf:"bytes,2,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	SystemDetails        *SystemDetails `protobuf:"bytes,3,opt,name=system_details,json=systemDetails,proto3" json:"system_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SDKFogfindRequest) Reset()         { *m = SDKFogfindRequest{} }
func (m *SDKFogfindRequest) String() string { return proto.CompactTextString(m) }
func (*SDKFogfindRequest) ProtoMessage()    {}
func (*SDKFogfindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{29}
}

func (m *SDKFogfindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKFogfindRequest.Unmarshal(m, b)
}
func (m *SDKFogfindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKFogfindRequest.Marshal(b, m, deterministic)
}
func (m *SDKFogfindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKFogfindRequest.Merge(m, src)
}
func (m *SDKFogfindRequest) XXX_Size() int {
	return xxx_messageInfo_SDKFogfindRequest.Size(m)
}
func (m *SDKFogfindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKFogfindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SDKFogfindRequest proto.InternalMessageInfo

func (m *SDKFogfindRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SDKFogfindRequest) GetDeviceKey() string {
	if m != nil {
		return m.DeviceKey
	}
	return ""
}

func (m *SDKFogfindRequest) GetSystemDetails() *SystemDetails {
	if m != nil {
		return m.SystemDetails
	}
	return nil
}

type SDKFogfindResponse struct {
	Build                bool     `protobuf:"varint,1,opt,name=build,proto3" json:"build,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	TotalSize            string   `protobuf:"bytes,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	Received             string   `protobuf:"bytes,4,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDKFogfindResponse) Reset()         { *m = SDKFogfindResponse{} }
func (m *SDKFogfindResponse) String() string { return proto.CompactTextString(m) }
func (*SDKFogfindResponse) ProtoMessage()    {}
func (*SDKFogfindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{30}
}

func (m *SDKFogfindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKFogfindResponse.Unmarshal(m, b)
}
func (m *SDKFogfindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKFogfindResponse.Marshal(b, m, deterministic)
}
func (m *SDKFogfindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKFogfindResponse.Merge(m, src)
}
func (m *SDKFogfindResponse) XXX_Size() int {
	return xxx_messageInfo_SDKFogfindResponse.Size(m)
}
func (m *SDKFogfindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKFogfindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SDKFogfindResponse proto.InternalMessageInfo

func (m *SDKFogfindResponse) GetBuild() bool {
	if m != nil {
		return m.Build
	}
	return false
}

func (m *SDKFogfindResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SDKFogfindResponse) GetTotalSize() string {
	if m != nil {
		return m.TotalSize
	}
	return ""
}

func (m *SDKFogfindResponse) GetReceived() string {
	if m != nil {
		return m.Received
	}
	return ""
}

type SystemDetails struct {
	SystemName               string                      `protobuf:"bytes,1,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	HardwareInterfaceDetails []*HardwareInterfaceDetails `protobuf:"bytes,2,rep,name=hardware_interface_details,json=hardwareInterfaceDetails,proto3" json:"hardware_interface_details,omitempty"`
	IpAddress                string                      `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os                       string                      `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Cpu                      string                      `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *SystemDetails) Reset()         { *m = SystemDetails{} }
func (m *SystemDetails) String() string { return proto.CompactTextString(m) }
func (*SystemDetails) ProtoMessage()    {}
func (*SystemDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{31}
}

func (m *SystemDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemDetails.Unmarshal(m, b)
}
func (m *SystemDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemDetails.Marshal(b, m, deterministic)
}
func (m *SystemDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemDetails.Merge(m, src)
}
func (m *SystemDetails) XXX_Size() int {
	return xxx_messageInfo_SystemDetails.Size(m)
}
func (m *SystemDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemDetails.DiscardUnknown(m)
}

var xxx_messageInfo_SystemDetails proto.InternalMessageInfo

func (m *SystemDetails) GetSystemName() string {
	if m != nil {
		return m.SystemName
	}
	return ""
}

func (m *SystemDetails) GetHardwareInterfaceDetails() []*HardwareInterfaceDetails {
	if m != nil {
		return m.HardwareInterfaceDetails
	}
	return nil
}

func (m *SystemDetails) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *SystemDetails) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *SystemDetails) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

type HardwareInterfaceDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Flag                 string   `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	HardwareAddress      string   `protobuf:"bytes,3,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	Index                int32    `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	MTU                  int32    `protobuf:"varint,5,opt,name=MTU,proto3" json:"MTU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardwareInterfaceDetails) Reset()         { *m = HardwareInterfaceDetails{} }
func (m *HardwareInterfaceDetails) String() string { return proto.CompactTextString(m) }
func (*HardwareInterfaceDetails) ProtoMessage()    {}
func (*HardwareInterfaceDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_db4d650e9f73de9c, []int{32}
}

func (m *HardwareInterfaceDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareInterfaceDetails.Unmarshal(m, b)
}
func (m *HardwareInterfaceDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareInterfaceDetails.Marshal(b, m, deterministic)
}
func (m *HardwareInterfaceDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareInterfaceDetails.Merge(m, src)
}
func (m *HardwareInterfaceDetails) XXX_Size() int {
	return xxx_messageInfo_HardwareInterfaceDetails.Size(m)
}
func (m *HardwareInterfaceDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareInterfaceDetails.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareInterfaceDetails proto.InternalMessageInfo

func (m *HardwareInterfaceDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HardwareInterfaceDetails) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *HardwareInterfaceDetails) GetHardwareAddress() string {
	if m != nil {
		return m.HardwareAddress
	}
	return ""
}

func (m *HardwareInterfaceDetails) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *HardwareInterfaceDetails) GetMTU() int32 {
	if m != nil {
		return m.MTU
	}
	return 0
}

func init() {
	proto.RegisterEnum("authpb.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*CheckServerStatusRequest)(nil), "authpb.CheckServerStatusRequest")
	proto.RegisterType((*CheckServerStatusResponse)(nil), "authpb.CheckServerStatusResponse")
	proto.RegisterType((*RegisterAccountRequest)(nil), "authpb.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "authpb.RegisterAccountResponse")
	proto.RegisterType((*GenerateDeviceKeyRequest)(nil), "authpb.GenerateDeviceKeyRequest")
	proto.RegisterType((*GenerateDeviceKeyResponse)(nil), "authpb.GenerateDeviceKeyResponse")
	proto.RegisterType((*LoginRequest)(nil), "authpb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "authpb.LoginResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "authpb.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "authpb.UpdateAccountResponse")
	proto.RegisterType((*GetAccountDetailsRequest)(nil), "authpb.GetAccountDetailsRequest")
	proto.RegisterType((*GetAccountDetailsResponse)(nil), "authpb.GetAccountDetailsResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "authpb.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "authpb.ChangePasswordResponse")
	proto.RegisterType((*GetAllAccountsRequest)(nil), "authpb.GetAllAccountsRequest")
	proto.RegisterType((*GetAllAccountsResponse)(nil), "authpb.GetAllAccountsResponse")
	proto.RegisterType((*GetAllSessionDetailsRequest)(nil), "authpb.GetAllSessionDetailsRequest")
	proto.RegisterType((*GetAllSessionDetailsResponse)(nil), "authpb.GetAllSessionDetailsResponse")
	proto.RegisterType((*CheckUsernameRequest)(nil), "authpb.CheckUsernameRequest")
	proto.RegisterType((*CheckUsernameResponse)(nil), "authpb.CheckUsernameResponse")
	proto.RegisterType((*UsernameAvailabilityRequest)(nil), "authpb.UsernameAvailabilityRequest")
	proto.RegisterType((*UsernameAvailabilityResponse)(nil), "authpb.UsernameAvailabilityResponse")
	proto.RegisterType((*EmailAvailabilityRequest)(nil), "authpb.EmailAvailabilityRequest")
	proto.RegisterType((*EmailAvailabilityResponse)(nil), "authpb.EmailAvailabilityResponse")
	proto.RegisterType((*GetSystemDetailsRequest)(nil), "authpb.GetSystemDetailsRequest")
	proto.RegisterType((*GetSystemDetailsResponse)(nil), "authpb.GetSystemDetailsResponse")
	proto.RegisterType((*Chunk)(nil), "authpb.Chunk")
	proto.RegisterType((*UploadRequest)(nil), "authpb.UploadRequest")
	proto.RegisterType((*UploadStatus)(nil), "authpb.UploadStatus")
	proto.RegisterType((*SDKFogfindRequest)(nil), "authpb.SDKFogfindRequest")
	proto.RegisterType((*SDKFogfindResponse)(nil), "authpb.SDKFogfindResponse")
	proto.RegisterType((*SystemDetails)(nil), "authpb.SystemDetails")
	proto.RegisterType((*HardwareInterfaceDetails)(nil), "authpb.HardwareInterfaceDetails")
}

func init() { proto.RegisterFile("authpb.proto", fileDescriptor_db4d650e9f73de9c) }

var fileDescriptor_db4d650e9f73de9c = []byte{
	// 1530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x5f, 0x6f, 0x1b, 0x37,
	0x12, 0xcf, 0x4a, 0x96, 0x6c, 0x8f, 0x24, 0x5b, 0xe6, 0x49, 0x8e, 0xbc, 0x76, 0x12, 0x7b, 0x73,
	0x01, 0x92, 0xe0, 0x90, 0xf8, 0x9c, 0x7b, 0x49, 0x90, 0x17, 0x9f, 0x13, 0x27, 0x46, 0x92, 0x4b,
	0x4e, 0xb2, 0x0f, 0x01, 0x0e, 0x38, 0x81, 0xd6, 0x52, 0x12, 0xa1, 0x15, 0x57, 0xb7, 0x4b, 0xd9,
	0x75, 0x0b, 0xf4, 0xa1, 0xe8, 0x43, 0x0b, 0xf4, 0xa1, 0x45, 0xdb, 0x2f, 0x51, 0xa0, 0x1f, 0xa6,
	0x28, 0xd0, 0x4f, 0xd0, 0x0f, 0x52, 0xf0, 0xdf, 0xfe, 0xf3, 0x4a, 0x30, 0x52, 0xa0, 0x7d, 0xdb,
	0x19, 0x0e, 0xc9, 0xe1, 0x6f, 0x7e, 0x33, 0xe4, 0x2c, 0x54, 0xf1, 0x94, 0x0f, 0x27, 0xa7, 0x0f,
	0x26, 0x81, 0xcf, 0x7d, 0x54, 0x56, 0x92, 0xbd, 0x35, 0xf0, 0xfd, 0x81, 0x47, 0x1e, 0xe2, 0x09,
	0x7d, 0x88, 0x19, 0xf3, 0x39, 0xe6, 0xd4, 0x67, 0xa1, 0xb2, 0x72, 0x6c, 0x68, 0x1d, 0x0c, 0x49,
	0x6f, 0xd4, 0x21, 0xc1, 0x19, 0x09, 0x3a, 0x1c, 0xf3, 0x69, 0xd8, 0x26, 0xff, 0x9f, 0x92, 0x90,
	0x3b, 0x5f, 0x5b, 0xb0, 0x91, 0x33, 0x18, 0x4e, 0x7c, 0x16, 0x12, 0x74, 0x0b, 0x2a, 0xa1, 0xd4,
	0x77, 0x19, 0x1e, 0x93, 0x96, 0xb5, 0x6d, 0xdd, 0x5d, 0x6e, 0x83, 0x52, 0xfd, 0x0b, 0x8f, 0x09,
	0x42, 0xb0, 0x30, 0xf4, 0x43, 0xde, 0x2a, 0xc8, 0x11, 0xf9, 0x2d, 0x74, 0x13, 0x3f, 0xe0, 0xad,
	0xa2, 0xd2, 0x89, 0x6f, 0xa1, 0xe3, 0x74, 0x4c, 0x5a, 0x0b, 0x4a, 0x27, 0xbe, 0xd1, 0x3a, 0x94,
	0x43, 0xb9, 0x5d, 0xab, 0x24, 0xb5, 0x5a, 0x72, 0xbe, 0x29, 0xc0, 0x7a, 0x9b, 0x0c, 0x68, 0xc8,
	0x49, 0xb0, 0xdf, 0xeb, 0xf9, 0x53, 0xc6, 0xb5, 0xb7, 0xe8, 0x06, 0x40, 0x9f, 0x06, 0x21, 0x4f,
	0xba, 0xb3, 0x2c, 0x35, 0xd2, 0x9b, 0x4d, 0x58, 0xf6, 0xb0, 0x19, 0x55, 0x2e, 0x2d, 0x09, 0x85,
	0x1c, 0xb4, 0x61, 0x69, 0x1a, 0x92, 0x40, 0x8e, 0x29, 0xd7, 0x22, 0x19, 0x35, 0xa0, 0x44, 0xc6,
	0x98, 0x7a, 0xda, 0x3f, 0x25, 0x88, 0x19, 0x13, 0x1c, 0x86, 0xe7, 0x7e, 0xe0, 0x6a, 0x17, 0x23,
	0x19, 0xdd, 0x83, 0x7a, 0xcf, 0x67, 0x7d, 0x1a, 0x8c, 0xbb, 0x91, 0x4d, 0x59, 0xda, 0xac, 0x6a,
	0xfd, 0x3b, 0x63, 0x7a, 0x1b, 0x6a, 0x3d, 0x7f, 0x3c, 0xc1, 0xec, 0xa2, 0xcb, 0x49, 0x30, 0x0e,
	0x5b, 0x8b, 0xdb, 0xd6, 0xdd, 0xa5, 0x76, 0x55, 0x2b, 0x8f, 0x85, 0x4e, 0x9c, 0x6c, 0xe0, 0x9f,
	0x71, 0x6d, 0xb1, 0x24, 0x2d, 0x96, 0x85, 0x46, 0x0e, 0x3b, 0x47, 0x70, 0xfd, 0x12, 0x24, 0x3a,
	0x46, 0xeb, 0x50, 0x0e, 0x48, 0x38, 0xf5, 0xb8, 0xc6, 0x43, 0x4b, 0x09, 0x78, 0x0b, 0x29, 0x78,
	0x1f, 0x41, 0xeb, 0x05, 0x61, 0x24, 0xc0, 0x9c, 0x3c, 0x23, 0x67, 0xb4, 0x47, 0x5e, 0x91, 0x0b,
	0x83, 0xef, 0x75, 0x58, 0x14, 0x98, 0x74, 0xa9, 0x6b, 0x16, 0x13, 0xe2, 0x91, 0xeb, 0x3c, 0x81,
	0x8d, 0x9c, 0x49, 0xda, 0x83, 0x1b, 0x00, 0xae, 0x54, 0x76, 0x47, 0xe4, 0xc2, 0x44, 0xc5, 0x35,
	0x66, 0xce, 0x21, 0x54, 0x5f, 0xfb, 0x03, 0xca, 0xcc, 0x26, 0xc9, 0x40, 0x58, 0x99, 0x40, 0x24,
	0x21, 0x2f, 0xa4, 0x21, 0x77, 0xee, 0x40, 0x4d, 0xaf, 0xa3, 0xf7, 0x6d, 0x40, 0x89, 0xfb, 0x23,
	0xc2, 0xf4, 0x2a, 0x4a, 0x70, 0x3e, 0xb7, 0xa0, 0x71, 0x32, 0x71, 0x31, 0x27, 0x7f, 0x26, 0x79,
	0x9c, 0x17, 0xd0, 0xcc, 0x78, 0xf1, 0x81, 0xf1, 0xb2, 0x45, 0xbc, 0xb8, 0x5e, 0xe5, 0x19, 0xe1,
	0x98, 0x7a, 0x51, 0xf6, 0x7e, 0x69, 0x89, 0xb8, 0x5c, 0x1a, 0x8c, 0xe3, 0xf2, 0x07, 0x1e, 0xf8,
	0x0b, 0x0b, 0x9a, 0x07, 0x43, 0xcc, 0x06, 0xc4, 0x30, 0xdf, 0x00, 0xbf, 0x03, 0x55, 0xdf, 0x73,
	0xe3, 0x3c, 0x51, 0x9e, 0x54, 0x7c, 0xcf, 0x8d, 0x72, 0x64, 0x07, 0xaa, 0x8c, 0x9c, 0x77, 0x33,
	0xb1, 0xaf, 0x30, 0x72, 0xfe, 0x6e, 0x5e, 0xc6, 0x15, 0x73, 0x33, 0xce, 0x79, 0x09, 0xeb, 0x59,
	0x4f, 0x3e, 0x10, 0xfc, 0x7d, 0x68, 0x0a, 0x7c, 0x3d, 0x4f, 0x43, 0x6c, 0x90, 0x17, 0x05, 0x2d,
	0x1c, 0xd1, 0x89, 0x34, 0x2f, 0xb6, 0xe5, 0xb7, 0xc0, 0xc5, 0xa3, 0x63, 0xaa, 0x2a, 0x5f, 0xb1,
	0xad, 0x04, 0xe7, 0x17, 0x0b, 0xd6, 0xb3, 0x6b, 0x68, 0x6f, 0xfe, 0x02, 0xa5, 0x7e, 0x3f, 0x4e,
	0xb6, 0x85, 0x7e, 0xff, 0xc8, 0xcd, 0x44, 0xad, 0x30, 0x37, 0x6a, 0xc5, 0x4c, 0xd4, 0x66, 0xd6,
	0xb1, 0x28, 0x96, 0xa5, 0x4c, 0x2c, 0x77, 0xa0, 0xda, 0x0b, 0x08, 0xe6, 0xc4, 0xed, 0xca, 0x02,
	0x5d, 0x96, 0xae, 0x57, 0xb4, 0xee, 0x38, 0x5d, 0xa7, 0x17, 0x53, 0xd8, 0xec, 0xc1, 0xa6, 0x3a,
	0x57, 0x87, 0x84, 0x21, 0xf5, 0x59, 0x9a, 0x9b, 0xb9, 0x87, 0x73, 0xbe, 0xb3, 0x60, 0x2b, 0x7f,
	0x52, 0x02, 0x92, 0x30, 0x39, 0x2b, 0x3c, 0x72, 0xe5, 0x99, 0xfd, 0xc1, 0x80, 0xb8, 0x5d, 0xca,
	0x22, 0xa6, 0x4a, 0xc5, 0x11, 0x43, 0x77, 0x60, 0xa5, 0x37, 0x0d, 0x02, 0xc2, 0x78, 0x57, 0xbb,
	0xa9, 0x50, 0xa9, 0x69, 0xad, 0xba, 0xd2, 0x22, 0xdc, 0x26, 0x94, 0x0d, 0x34, 0x3c, 0x12, 0xb7,
	0x77, 0x94, 0x0d, 0x9c, 0x3d, 0x68, 0xc8, 0x4b, 0xf0, 0x44, 0xc3, 0x72, 0x85, 0x52, 0xe5, 0xbc,
	0x12, 0x74, 0x4f, 0xcd, 0xd1, 0x47, 0x98, 0x57, 0xdf, 0xd6, 0xa1, 0x8c, 0xcf, 0x30, 0xc7, 0x81,
	0xe1, 0x99, 0x92, 0x9c, 0xc7, 0xb0, 0x69, 0xd6, 0xd9, 0x3f, 0xc3, 0xd4, 0xc3, 0xa7, 0xd4, 0xa3,
	0xfc, 0xe2, 0x2a, 0x7e, 0x3c, 0x85, 0xad, 0xfc, 0xa9, 0xda, 0x9d, 0x2d, 0x58, 0xc6, 0x4a, 0xef,
	0xa9, 0xc9, 0x4b, 0xed, 0x58, 0xe1, 0xec, 0x42, 0xeb, 0xb9, 0x20, 0x49, 0xde, 0xae, 0x11, 0x9b,
	0xac, 0x64, 0x9e, 0x3f, 0x86, 0x8d, 0x9c, 0x19, 0x57, 0xda, 0xec, 0x07, 0x0b, 0xae, 0xbf, 0x20,
	0xbc, 0x73, 0x11, 0x72, 0x32, 0xce, 0xd0, 0xe5, 0x36, 0xd4, 0x86, 0x38, 0x70, 0xcf, 0x71, 0x40,
	0x92, 0xf5, 0xaa, 0x6a, 0x94, 0x92, 0xdf, 0xf7, 0xa0, 0x1e, 0x19, 0x61, 0xd7, 0x0d, 0x48, 0x68,
	0x12, 0x76, 0xd5, 0xe8, 0xf7, 0x95, 0x5a, 0xa4, 0x11, 0x9d, 0x44, 0x46, 0x8a, 0x12, 0xcb, 0x74,
	0x62, 0x86, 0x57, 0xa0, 0xe0, 0x87, 0x9a, 0x07, 0x05, 0x3f, 0x44, 0x75, 0x28, 0xf6, 0x26, 0x53,
	0x9d, 0x1e, 0xe2, 0xd3, 0x79, 0x2d, 0xeb, 0x6e, 0xc6, 0xd7, 0xb8, 0x8c, 0x68, 0xae, 0x59, 0xc9,
	0x94, 0x40, 0x2d, 0x58, 0x1c, 0x93, 0x30, 0xc4, 0x03, 0x93, 0xb8, 0x46, 0x74, 0xfe, 0x0b, 0xa5,
	0x83, 0xe1, 0x94, 0x8d, 0x84, 0xc9, 0x81, 0xcf, 0x38, 0x61, 0xaa, 0x04, 0x55, 0xdb, 0x46, 0x14,
	0xd8, 0x71, 0x9f, 0x63, 0xaf, 0x43, 0x3f, 0x8e, 0xf2, 0x3e, 0x52, 0x08, 0x0a, 0x04, 0xa4, 0x47,
	0xe8, 0x19, 0x31, 0x65, 0x2f, 0x92, 0x9d, 0x55, 0xa8, 0x9d, 0x4c, 0x3c, 0x1f, 0x9b, 0x8a, 0xeb,
	0xfc, 0x07, 0xaa, 0x4a, 0xd1, 0x89, 0xfc, 0x7a, 0xa3, 0xfd, 0x52, 0x0e, 0x1b, 0x11, 0xfd, 0x0d,
	0x16, 0x0e, 0x7c, 0x57, 0xed, 0xb7, 0xb2, 0xd7, 0x7a, 0xa0, 0x9f, 0x97, 0xc9, 0xd9, 0x62, 0xbc,
	0x2d, 0xad, 0x9c, 0xaf, 0x2c, 0x58, 0xeb, 0x3c, 0x7b, 0x75, 0xe8, 0x0f, 0xfa, 0x94, 0xb9, 0x57,
	0xb9, 0xd0, 0xd3, 0x6f, 0x83, 0x42, 0xe6, 0x6d, 0x80, 0x9e, 0xc2, 0x4a, 0x28, 0x11, 0xee, 0xba,
	0x0a, 0x62, 0x79, 0xb6, 0xca, 0x5e, 0xd3, 0x38, 0x92, 0xc6, 0xbf, 0x16, 0x26, 0x45, 0xe7, 0x53,
	0x40, 0x49, 0x6f, 0xe2, 0x67, 0xc1, 0xe9, 0x94, 0x7a, 0xae, 0xe6, 0x9f, 0x12, 0x92, 0xb8, 0x17,
	0xe6, 0xe0, 0x5e, 0x9c, 0x87, 0xfb, 0x42, 0x06, 0xf7, 0x9f, 0x2c, 0xa8, 0xa5, 0x1c, 0x94, 0x0f,
	0x66, 0x75, 0x9e, 0xd4, 0x83, 0x59, 0xaa, 0x24, 0x83, 0xff, 0x07, 0x76, 0xc4, 0x60, 0xca, 0x38,
	0x09, 0xfa, 0xb8, 0x47, 0xa2, 0xc3, 0x17, 0xb6, 0x8b, 0x77, 0x2b, 0x7b, 0xdb, 0xe6, 0xf0, 0x2f,
	0xb5, 0xe5, 0x91, 0x31, 0x34, 0x38, 0xb4, 0x86, 0x33, 0x46, 0x7e, 0x3f, 0xed, 0xbf, 0xb7, 0xa0,
	0x35, 0x6b, 0x5f, 0x71, 0xeb, 0x25, 0xce, 0x25, 0xbf, 0x85, 0xae, 0xef, 0xe1, 0x81, 0x69, 0x01,
	0xc4, 0x77, 0x6e, 0x9e, 0x16, 0xf3, 0xf3, 0xb4, 0x01, 0x25, 0xca, 0x5c, 0xf2, 0x91, 0x74, 0xaa,
	0xd4, 0x56, 0x82, 0xf0, 0xeb, 0xcd, 0xf1, 0x89, 0xf4, 0xab, 0xd4, 0x16, 0x9f, 0xf7, 0x1f, 0x41,
	0x3d, 0x4b, 0x4a, 0x54, 0x81, 0xc5, 0x13, 0x36, 0x62, 0xfe, 0x39, 0xab, 0x5f, 0x43, 0x65, 0x28,
	0xbc, 0x1d, 0xd5, 0x2d, 0x04, 0x50, 0x3e, 0xc4, 0xd4, 0x23, 0x6e, 0xbd, 0xb0, 0xf7, 0x23, 0x40,
	0x65, 0x7f, 0xca, 0x87, 0xa2, 0xb9, 0xa1, 0x3d, 0x82, 0x3e, 0x81, 0xb5, 0x4b, 0xcd, 0x0e, 0x8a,
	0xe0, 0x9e, 0xd5, 0x24, 0xd9, 0x3b, 0x73, 0x2c, 0x14, 0xe9, 0x9c, 0x9d, 0xcf, 0x7e, 0xfe, 0xf5,
	0xdb, 0xc2, 0x26, 0xda, 0x90, 0x3d, 0xd8, 0xd9, 0xdf, 0x1f, 0xf6, 0x84, 0xa9, 0xea, 0x94, 0x74,
	0x71, 0x60, 0x50, 0x4b, 0x5d, 0x18, 0x68, 0x2b, 0xb5, 0x6c, 0xe6, 0xee, 0xb1, 0x6f, 0xcc, 0x18,
	0xd5, 0x1b, 0x6e, 0xcb, 0x0d, 0x6d, 0xa7, 0x99, 0xda, 0xd0, 0xe4, 0xdd, 0x13, 0xeb, 0x3e, 0xda,
	0x87, 0x66, 0x87, 0x30, 0xf7, 0x9f, 0x82, 0xfe, 0x87, 0xd4, 0x23, 0xc7, 0xfe, 0x81, 0x47, 0x05,
	0xe1, 0x9b, 0xe9, 0x2c, 0x37, 0x1b, 0xd6, 0xe2, 0x0d, 0xa7, 0x6c, 0xe4, 0x5c, 0xdb, 0xb5, 0xd0,
	0x73, 0x80, 0x38, 0xc1, 0xd0, 0x46, 0x94, 0x94, 0xd9, 0x12, 0x60, 0xdb, 0x79, 0x43, 0xca, 0xd3,
	0x5d, 0x0b, 0xbd, 0x87, 0xb5, 0x4b, 0xdd, 0x43, 0x0c, 0xfb, 0xac, 0x6e, 0x24, 0x86, 0x7d, 0x76,
	0xeb, 0x71, 0x02, 0xf5, 0x6c, 0x91, 0x46, 0xb7, 0xe2, 0x69, 0xb9, 0x57, 0x8d, 0xbd, 0x3d, 0xdb,
	0x40, 0x2f, 0x8b, 0xa1, 0x91, 0x77, 0xa7, 0xa2, 0xdb, 0x11, 0x72, 0xb3, 0x2f, 0x6b, 0xfb, 0xaf,
	0xf3, 0x8d, 0xf4, 0x16, 0xef, 0x61, 0xed, 0xd2, 0x35, 0x1a, 0x63, 0x32, 0xeb, 0x4e, 0x8e, 0x31,
	0x99, 0x7d, 0x07, 0xb7, 0x61, 0x35, 0xd3, 0x2b, 0xa2, 0x9b, 0x66, 0x56, 0x7e, 0x5f, 0x6d, 0xdf,
	0x9a, 0x39, 0xae, 0xd7, 0xfc, 0x07, 0x94, 0x64, 0xef, 0x85, 0x1a, 0xc6, 0x32, 0xd9, 0xd2, 0xd9,
	0xcd, 0x8c, 0x56, 0xcf, 0x7a, 0x2d, 0xee, 0xa5, 0x44, 0x0f, 0x14, 0x33, 0x3e, 0xaf, 0x41, 0x8b,
	0x19, 0x9f, 0xdf, 0x38, 0x49, 0x16, 0x65, 0x7a, 0x9d, 0x24, 0x8b, 0xf2, 0x7b, 0xa4, 0x24, 0x8b,
	0x66, 0x35, 0x4a, 0x6f, 0x61, 0x25, 0xdd, 0x2f, 0xa0, 0x44, 0xf2, 0xe5, 0x74, 0x34, 0xf6, 0xcd,
	0x59, 0xc3, 0x7a, 0xc1, 0x7f, 0xc3, 0x4a, 0xfa, 0xc9, 0x1f, 0x2f, 0x98, 0xdb, 0x4e, 0xc4, 0x0b,
	0xe6, 0x77, 0x0a, 0xbb, 0x16, 0xea, 0x41, 0x23, 0xef, 0xe1, 0x1c, 0x53, 0x72, 0xce, 0x5b, 0x3c,
	0xa6, 0xe4, 0xbc, 0xb7, 0xf7, 0xae, 0x75, 0x5a, 0x96, 0x3f, 0x8c, 0x1e, 0xfd, 0x16, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xd5, 0x31, 0xba, 0x66, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error)
	CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error)
	SendBuildFileToClient(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (AuthService_SendBuildFileToClientClient, error)
	SDKFogfind(ctx context.Context, in *SDKFogfindRequest, opts ...grpc.CallOption) (AuthService_SDKFogfindClient, error)
	GenerateDeviceKey(ctx context.Context, in *GenerateDeviceKeyRequest, opts ...grpc.CallOption) (*GenerateDeviceKeyResponse, error)
	GetSystemDetails(ctx context.Context, in *GetSystemDetailsRequest, opts ...grpc.CallOption) (*GetSystemDetailsResponse, error)
	UsernameAvailability(ctx context.Context, in *UsernameAvailabilityRequest, opts ...grpc.CallOption) (*UsernameAvailabilityResponse, error)
	EmailAvailability(ctx context.Context, in *EmailAvailabilityRequest, opts ...grpc.CallOption) (*EmailAvailabilityResponse, error)
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	GetAccountDetails(ctx context.Context, in *GetAccountDetailsRequest, opts ...grpc.CallOption) (*GetAccountDetailsResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (AuthService_GetAllAccountsClient, error)
	GetAllSessionDetails(ctx context.Context, in *GetAllSessionDetailsRequest, opts ...grpc.CallOption) (AuthService_GetAllSessionDetailsClient, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error) {
	out := new(CheckServerStatusResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/CheckServerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error) {
	out := new(CheckUsernameResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/CheckUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SendBuildFileToClient(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (AuthService_SendBuildFileToClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[0], "/authpb.AuthService/SendBuildFileToClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceSendBuildFileToClientClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_SendBuildFileToClientClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type authServiceSendBuildFileToClientClient struct {
	grpc.ClientStream
}

func (x *authServiceSendBuildFileToClientClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authServiceClient) SDKFogfind(ctx context.Context, in *SDKFogfindRequest, opts ...grpc.CallOption) (AuthService_SDKFogfindClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[1], "/authpb.AuthService/SDKFogfind", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceSDKFogfindClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_SDKFogfindClient interface {
	Recv() (*SDKFogfindResponse, error)
	grpc.ClientStream
}

type authServiceSDKFogfindClient struct {
	grpc.ClientStream
}

func (x *authServiceSDKFogfindClient) Recv() (*SDKFogfindResponse, error) {
	m := new(SDKFogfindResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authServiceClient) GenerateDeviceKey(ctx context.Context, in *GenerateDeviceKeyRequest, opts ...grpc.CallOption) (*GenerateDeviceKeyResponse, error) {
	out := new(GenerateDeviceKeyResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/GenerateDeviceKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetSystemDetails(ctx context.Context, in *GetSystemDetailsRequest, opts ...grpc.CallOption) (*GetSystemDetailsResponse, error) {
	out := new(GetSystemDetailsResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/GetSystemDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UsernameAvailability(ctx context.Context, in *UsernameAvailabilityRequest, opts ...grpc.CallOption) (*UsernameAvailabilityResponse, error) {
	out := new(UsernameAvailabilityResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/UsernameAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EmailAvailability(ctx context.Context, in *EmailAvailabilityRequest, opts ...grpc.CallOption) (*EmailAvailabilityResponse, error) {
	out := new(EmailAvailabilityResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/EmailAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAccountDetails(ctx context.Context, in *GetAccountDetailsRequest, opts ...grpc.CallOption) (*GetAccountDetailsResponse, error) {
	out := new(GetAccountDetailsResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/GetAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (AuthService_GetAllAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[2], "/authpb.AuthService/GetAllAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceGetAllAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_GetAllAccountsClient interface {
	Recv() (*GetAllAccountsResponse, error)
	grpc.ClientStream
}

type authServiceGetAllAccountsClient struct {
	grpc.ClientStream
}

func (x *authServiceGetAllAccountsClient) Recv() (*GetAllAccountsResponse, error) {
	m := new(GetAllAccountsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authServiceClient) GetAllSessionDetails(ctx context.Context, in *GetAllSessionDetailsRequest, opts ...grpc.CallOption) (AuthService_GetAllSessionDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[3], "/authpb.AuthService/GetAllSessionDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceGetAllSessionDetailsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_GetAllSessionDetailsClient interface {
	Recv() (*GetAllSessionDetailsResponse, error)
	grpc.ClientStream
}

type authServiceGetAllSessionDetailsClient struct {
	grpc.ClientStream
}

func (x *authServiceGetAllSessionDetailsClient) Recv() (*GetAllSessionDetailsResponse, error) {
	m := new(GetAllSessionDetailsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CheckServerStatus(context.Context, *CheckServerStatusRequest) (*CheckServerStatusResponse, error)
	CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameResponse, error)
	SendBuildFileToClient(*UploadRequest, AuthService_SendBuildFileToClientServer) error
	SDKFogfind(*SDKFogfindRequest, AuthService_SDKFogfindServer) error
	GenerateDeviceKey(context.Context, *GenerateDeviceKeyRequest) (*GenerateDeviceKeyResponse, error)
	GetSystemDetails(context.Context, *GetSystemDetailsRequest) (*GetSystemDetailsResponse, error)
	UsernameAvailability(context.Context, *UsernameAvailabilityRequest) (*UsernameAvailabilityResponse, error)
	EmailAvailability(context.Context, *EmailAvailabilityRequest) (*EmailAvailabilityResponse, error)
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	GetAccountDetails(context.Context, *GetAccountDetailsRequest) (*GetAccountDetailsResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	GetAllAccounts(*GetAllAccountsRequest, AuthService_GetAllAccountsServer) error
	GetAllSessionDetails(*GetAllSessionDetailsRequest, AuthService_GetAllSessionDetailsServer) error
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CheckServerStatus(ctx context.Context, req *CheckServerStatusRequest) (*CheckServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerStatus not implemented")
}
func (*UnimplementedAuthServiceServer) CheckUsername(ctx context.Context, req *CheckUsernameRequest) (*CheckUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsername not implemented")
}
func (*UnimplementedAuthServiceServer) SendBuildFileToClient(req *UploadRequest, srv AuthService_SendBuildFileToClientServer) error {
	return status.Errorf(codes.Unimplemented, "method SendBuildFileToClient not implemented")
}
func (*UnimplementedAuthServiceServer) SDKFogfind(req *SDKFogfindRequest, srv AuthService_SDKFogfindServer) error {
	return status.Errorf(codes.Unimplemented, "method SDKFogfind not implemented")
}
func (*UnimplementedAuthServiceServer) GenerateDeviceKey(ctx context.Context, req *GenerateDeviceKeyRequest) (*GenerateDeviceKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDeviceKey not implemented")
}
func (*UnimplementedAuthServiceServer) GetSystemDetails(ctx context.Context, req *GetSystemDetailsRequest) (*GetSystemDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemDetails not implemented")
}
func (*UnimplementedAuthServiceServer) UsernameAvailability(ctx context.Context, req *UsernameAvailabilityRequest) (*UsernameAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameAvailability not implemented")
}
func (*UnimplementedAuthServiceServer) EmailAvailability(ctx context.Context, req *EmailAvailabilityRequest) (*EmailAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailAvailability not implemented")
}
func (*UnimplementedAuthServiceServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*UpdateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedAuthServiceServer) GetAccountDetails(ctx context.Context, req *GetAccountDetailsRequest) (*GetAccountDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountDetails not implemented")
}
func (*UnimplementedAuthServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAuthServiceServer) GetAllAccounts(req *GetAllAccountsRequest, srv AuthService_GetAllAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllAccounts not implemented")
}
func (*UnimplementedAuthServiceServer) GetAllSessionDetails(req *GetAllSessionDetailsRequest, srv AuthService_GetAllSessionDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllSessionDetails not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CheckServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/CheckServerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, req.(*CheckServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/CheckUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUsername(ctx, req.(*CheckUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SendBuildFileToClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UploadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).SendBuildFileToClient(m, &authServiceSendBuildFileToClientServer{stream})
}

type AuthService_SendBuildFileToClientServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type authServiceSendBuildFileToClientServer struct {
	grpc.ServerStream
}

func (x *authServiceSendBuildFileToClientServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func _AuthService_SDKFogfind_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SDKFogfindRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).SDKFogfind(m, &authServiceSDKFogfindServer{stream})
}

type AuthService_SDKFogfindServer interface {
	Send(*SDKFogfindResponse) error
	grpc.ServerStream
}

type authServiceSDKFogfindServer struct {
	grpc.ServerStream
}

func (x *authServiceSDKFogfindServer) Send(m *SDKFogfindResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AuthService_GenerateDeviceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDeviceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateDeviceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/GenerateDeviceKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateDeviceKey(ctx, req.(*GenerateDeviceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetSystemDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetSystemDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/GetSystemDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetSystemDetails(ctx, req.(*GetSystemDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UsernameAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UsernameAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/UsernameAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UsernameAvailability(ctx, req.(*UsernameAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EmailAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EmailAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/EmailAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EmailAvailability(ctx, req.(*EmailAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/GetAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAccountDetails(ctx, req.(*GetAccountDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAllAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllAccountsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).GetAllAccounts(m, &authServiceGetAllAccountsServer{stream})
}

type AuthService_GetAllAccountsServer interface {
	Send(*GetAllAccountsResponse) error
	grpc.ServerStream
}

type authServiceGetAllAccountsServer struct {
	grpc.ServerStream
}

func (x *authServiceGetAllAccountsServer) Send(m *GetAllAccountsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AuthService_GetAllSessionDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllSessionDetailsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).GetAllSessionDetails(m, &authServiceGetAllSessionDetailsServer{stream})
}

type AuthService_GetAllSessionDetailsServer interface {
	Send(*GetAllSessionDetailsResponse) error
	grpc.ServerStream
}

type authServiceGetAllSessionDetailsServer struct {
	grpc.ServerStream
}

func (x *authServiceGetAllSessionDetailsServer) Send(m *GetAllSessionDetailsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckServerStatus",
			Handler:    _AuthService_CheckServerStatus_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _AuthService_CheckUsername_Handler,
		},
		{
			MethodName: "GenerateDeviceKey",
			Handler:    _AuthService_GenerateDeviceKey_Handler,
		},
		{
			MethodName: "GetSystemDetails",
			Handler:    _AuthService_GetSystemDetails_Handler,
		},
		{
			MethodName: "UsernameAvailability",
			Handler:    _AuthService_UsernameAvailability_Handler,
		},
		{
			MethodName: "EmailAvailability",
			Handler:    _AuthService_EmailAvailability_Handler,
		},
		{
			MethodName: "RegisterAccount",
			Handler:    _AuthService_RegisterAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AuthService_UpdateAccount_Handler,
		},
		{
			MethodName: "GetAccountDetails",
			Handler:    _AuthService_GetAccountDetails_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendBuildFileToClient",
			Handler:       _AuthService_SendBuildFileToClient_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SDKFogfind",
			Handler:       _AuthService_SDKFogfind_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllAccounts",
			Handler:       _AuthService_GetAllAccounts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllSessionDetails",
			Handler:       _AuthService_GetAllSessionDetails_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "authpb.proto",
}
